from spacepy import pycdf
import os

wind_csv = open('wind.csv', 'a')
wind_csv.write('Alpha_Na_nonlin,Alpha_VX_nonlin,Alpha_VY_nonlin,Alpha_VZ_nonlin,Alpha_V_nonlin,Alpha_W_nonlin,Alpha_Wpar_nonlin,Alpha_Wperp_nonlin,Alpha_sigmaNa_nonlin,Alpha_sigmaVX_nonlin,Alpha_sigmaVY_nonlin,Alpha_sigmaVZ_nonlin,Alpha_sigmaV_nonlin,Alpha_sigmaW_nonlin,Alpha_sigmaWpar_nonlin,Alpha_sigmaWperp_nonlin,Ang_dev,BX,BY,BZ,ChisQ_DOF_nonlin,EW_flowangle,Epoch,NS_flowangle,Peak_doy,Proton_Np_moment,Proton_Np_nonlin,Proton_VX_moment,Proton_VX_nonlin,Proton_VY_moment,Proton_VY_nonlin,Proton_VZ_moment,Proton_VZ_nonlin,Proton_V_moment,Proton_V_nonlin,Proton_W_moment,Proton_W_nonlin,Proton_Wpar_moment,Proton_Wpar_nonlin,Proton_Wperp_moment,Proton_Wperp_nonlin,Proton_sigmaNp_nonlin,Proton_sigmaVX_nonlin,Proton_sigmaVY_nonlin,Proton_sigmaVZ_nonlin,Proton_sigmaV_nonlin,Proton_sigmaW_nonlin,Proton_sigmaWpar_nonlin,Proton_sigmaWperp_nonlin,SigmaEW_flowangle,SigmaNS_flowangle,dev,doy,fit_flag,sigmaPeak_doy,xgse,year,ygse,ygsm,zgse,zgsm\n')
for root, dirs, files in os.walk('.\\'):
	for name in files:
		if 'cdf' in name:
			cdf_file = pycdf.CDF(name)
			for i in range(len(cdf_file['Epoch'])):
				wind_csv.write(str(cdf_file['Alpha_Na_nonlin'][i]) + ',' + str(cdf_file['Alpha_VX_nonlin'][i]) + ',' + str(cdf_file['Alpha_VY_nonlin'][i]) + ',' + str(cdf_file['Alpha_VZ_nonlin'][i])+ ',' + str(cdf_file['Alpha_V_nonlin'][i])+ ',' + str(cdf_file['Alpha_W_nonlin'][i])+ ',' + str(cdf_file['Alpha_Wpar_nonlin'][i])+ ',' + str(cdf_file['Alpha_Wperp_nonlin'][i])+ ',' + str(cdf_file['Alpha_sigmaNa_nonlin'][i])+ ',' + str(cdf_file['Alpha_sigmaVX_nonlin'][i])+ ',' + str(cdf_file['Alpha_sigmaVY_nonlin'][i])+ ',' + str(cdf_file['Alpha_sigmaVZ_nonlin'][i])+ ',' + str(cdf_file['Alpha_sigmaV_nonlin'][i])+ ',' + str(cdf_file['Alpha_sigmaW_nonlin'][i])+ ',' + str(cdf_file['Alpha_sigmaWpar_nonlin'][i])+ ',' + str(cdf_file['Alpha_sigmaWperp_nonlin'][i])+ ',' + str(cdf_file['Ang_dev'][i])+ ',' + str(cdf_file['BX'][i])+ ',' + str(cdf_file['BY'][i])+ ',' + str(cdf_file['BZ'][i])+ ',' + str(cdf_file['ChisQ_DOF_nonlin'][i])+ ',' + str(cdf_file['EW_flowangle'][i])+ ',' + str(cdf_file['Epoch'][i])+ ',' + str(cdf_file['NS_flowangle'][i])+ ',' + str(cdf_file['Peak_doy'][i])+ ',' + str(cdf_file['Proton_Np_moment'][i])+ ',' + str(cdf_file['Proton_Np_nonlin'][i])+ ',' + str(cdf_file['Proton_VX_moment'][i])+ ',' + str(cdf_file['Proton_VX_nonlin'][i])+ ',' + str(cdf_file['Proton_VY_moment'][i])+ ',' + str(cdf_file['Proton_VY_nonlin'][i])+ ',' + str(cdf_file['Proton_VZ_moment'][i])+ ',' + str(cdf_file['Proton_VZ_nonlin'][i])+ ',' + str(cdf_file['Proton_V_moment'][i])+ ',' + str(cdf_file['Proton_V_nonlin'][i])+ ',' + str(cdf_file['Proton_W_moment'][i])+ ',' + str(cdf_file['Proton_W_nonlin'][i])+ ',' + str(cdf_file['Proton_Wpar_moment'][i])+ ',' + str(cdf_file['Proton_Wpar_nonlin'][i])+ ',' + str(cdf_file['Proton_Wperp_moment'][i])+ ',' + str(cdf_file['Proton_Wperp_nonlin'][i])+ ',' + str(cdf_file['Proton_sigmaNp_nonlin'][i])+ ',' + str(cdf_file['Proton_sigmaVX_nonlin'][i])+ ',' + str(cdf_file['Proton_sigmaVY_nonlin'][i])+ ',' + str(cdf_file['Proton_sigmaVZ_nonlin'][i])+ ',' + str(cdf_file['Proton_sigmaV_nonlin'][i])+ ',' + str(cdf_file['Proton_sigmaW_nonlin'][i])+ ',' + str(cdf_file['Proton_sigmaWpar_nonlin'][i])+ ',' + str(cdf_file['Proton_sigmaWperp_nonlin'][i])+ ',' + str(cdf_file['SigmaEW_flowangle'][i])+ ',' + str(cdf_file['dev'][i])+ ',' + str(cdf_file['doy'][i])+  ',' + str(cdf_file['fit_flag'][i]) + ',' + str(cdf_file['sigmaPeak_doy'][i]) +',' + str(cdf_file['xgse'][i]) + ',' + str(cdf_file['year'][i]) + ',' + str(cdf_file['ygse'][i]) + ',' + str(cdf_file['ygsm'][i]) +  ',' + str(cdf_file['zgse'][i]) + ',' + str(cdf_file['zgsm'][i]) + '\n')
wind_csv.close()
